// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASJjTLI_PGbLjAy9TtyMeDLTYMalYSSGY',
    appId: '1:484652497825:web:562df588e60d99af79a9e0',
    messagingSenderId: '484652497825',
    projectId: 'billing-application-9a962',
    authDomain: 'billing-application-9a962.firebaseapp.com',
    storageBucket: 'billing-application-9a962.firebasestorage.app',
    measurementId: 'G-FQY4JDH66G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIuL1CHkeowQoUQ8jEw21N3cdECjtzgJ8',
    appId: '1:484652497825:android:e023f60e646daa7879a9e0',
    messagingSenderId: '484652497825',
    projectId: 'billing-application-9a962',
    storageBucket: 'billing-application-9a962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9tcinEY7LhQCS-QDDwJ89ffpi3AcWhuI',
    appId: '1:484652497825:ios:f9ff947852a1194179a9e0',
    messagingSenderId: '484652497825',
    projectId: 'billing-application-9a962',
    storageBucket: 'billing-application-9a962.firebasestorage.app',
    iosBundleId: 'com.example.billingApplication',
  );
}
